import { TarotCard } from "./types";

// =============================================
// MAZO COMPLETO DE TAROT: 78 CARTAS
// 22 Arcanos Mayores + 56 Arcanos Menores
// =============================================

export const MAJOR_ARCANA: TarotCard[] = [
  { id: 0, name: "The Fool", nameEs: "El Loco", arcana: "major", suit: null, element: "air", number: 0, keywords: ["inicio", "aventura", "inocencia", "espontaneidad"], meaningUpright: "Nuevos comienzos, fe en el universo, aventura inesperada. Es momento de dar el salto sin miedo.", meaningReversed: "Imprudencia, miedo al cambio, decision apresurada. Reflexiona antes de actuar.", imageSlug: "fool" },
  { id: 1, name: "The Magician", nameEs: "El Mago", arcana: "major", suit: null, element: "air", number: 1, keywords: ["poder", "manifestacion", "habilidad", "voluntad"], meaningUpright: "Tienes todos los recursos para manifestar lo que deseas. Confia en tu poder personal.", meaningReversed: "Manipulacion, talentos desperdiciados, falta de direccion. Cuidado con las ilusiones.", imageSlug: "magician" },
  { id: 2, name: "The High Priestess", nameEs: "La Sacerdotisa", arcana: "major", suit: null, element: "water", number: 2, keywords: ["intuicion", "misterio", "sabiduria", "subconsciente"], meaningUpright: "Escucha tu voz interior. La respuesta que buscas ya esta dentro de ti.", meaningReversed: "Secretos ocultos, desconexion con la intuicion, informacion retenida.", imageSlug: "high-priestess" },
  { id: 3, name: "The Empress", nameEs: "La Emperatriz", arcana: "major", suit: null, element: "earth", number: 3, keywords: ["abundancia", "fertilidad", "naturaleza", "sensualidad"], meaningUpright: "Abundancia y creatividad fluyen hacia ti. Conecta con tu lado nurturing y sensual.", meaningReversed: "Dependencia emocional, bloqueo creativo, negligencia del autocuidado.", imageSlug: "empress" },
  { id: 4, name: "The Emperor", nameEs: "El Emperador", arcana: "major", suit: null, element: "fire", number: 4, keywords: ["autoridad", "estructura", "liderazgo", "estabilidad"], meaningUpright: "Es momento de tomar el control con firmeza y disciplina. Establece limites claros.", meaningReversed: "Rigidez, autoritarismo, falta de disciplina, abuso de poder.", imageSlug: "emperor" },
  { id: 5, name: "The Hierophant", nameEs: "El Hierofante", arcana: "major", suit: null, element: "earth", number: 5, keywords: ["tradicion", "ensenanza", "espiritualidad", "conformidad"], meaningUpright: "Busca guia en la tradicion y la sabiduria antigua. Un mentor puede aparecer.", meaningReversed: "Rebelion contra lo establecido, dogmatismo, necesidad de buscar tu propio camino.", imageSlug: "hierophant" },
  { id: 6, name: "The Lovers", nameEs: "Los Enamorados", arcana: "major", suit: null, element: "air", number: 6, keywords: ["amor", "union", "eleccion", "armonia"], meaningUpright: "Una eleccion importante en el amor o los valores. La union y la armonia estan cerca.", meaningReversed: "Desequilibrio en relaciones, eleccion dificil, desalineacion de valores.", imageSlug: "lovers" },
  { id: 7, name: "The Chariot", nameEs: "El Carro", arcana: "major", suit: null, element: "water", number: 7, keywords: ["victoria", "determinacion", "control", "avance"], meaningUpright: "Victoria a traves de la voluntad y la determinacion. Avanza con confianza.", meaningReversed: "Falta de control, agresion, obstaculos, direccion perdida.", imageSlug: "chariot" },
  { id: 8, name: "Strength", nameEs: "La Fuerza", arcana: "major", suit: null, element: "fire", number: 8, keywords: ["coraje", "paciencia", "compasion", "fortaleza"], meaningUpright: "Tu verdadera fuerza viene de la compasion y la paciencia, no de la fuerza bruta.", meaningReversed: "Inseguridad, debilidad interior, falta de coraje, dudas constantes.", imageSlug: "strength" },
  { id: 9, name: "The Hermit", nameEs: "El Ermitano", arcana: "major", suit: null, element: "earth", number: 9, keywords: ["introspeccion", "soledad", "busqueda", "sabiduria"], meaningUpright: "Es momento de retirarte y buscar respuestas en tu interior. La soledad trae claridad.", meaningReversed: "Aislamiento excesivo, rechazo a la guia, soledad no deseada.", imageSlug: "hermit" },
  { id: 10, name: "Wheel of Fortune", nameEs: "La Rueda de la Fortuna", arcana: "major", suit: null, element: "fire", number: 10, keywords: ["destino", "ciclos", "cambio", "suerte"], meaningUpright: "Un giro del destino esta por llegar. Los ciclos cambian a tu favor.", meaningReversed: "Mala suerte temporal, resistencia al cambio, ciclos negativos.", imageSlug: "wheel" },
  { id: 11, name: "Justice", nameEs: "La Justicia", arcana: "major", suit: null, element: "air", number: 11, keywords: ["verdad", "equilibrio", "causa-efecto", "justicia"], meaningUpright: "La verdad saldra a la luz. Toma decisiones justas y acepta las consecuencias.", meaningReversed: "Injusticia, deshonestidad, falta de responsabilidad, parcialidad.", imageSlug: "justice" },
  { id: 12, name: "The Hanged Man", nameEs: "El Colgado", arcana: "major", suit: null, element: "water", number: 12, keywords: ["pausa", "sacrificio", "perspectiva", "rendicion"], meaningUpright: "A veces rendirse es ganar. Cambia tu perspectiva y encontraras la solucion.", meaningReversed: "Estancamiento, resistencia a soltar, sacrificio innecesario.", imageSlug: "hanged-man" },
  { id: 13, name: "Death", nameEs: "La Muerte", arcana: "major", suit: null, element: "water", number: 13, keywords: ["transformacion", "fin", "renacimiento", "transicion"], meaningUpright: "Un ciclo termina para que otro comience. Acepta la transformacion necesaria.", meaningReversed: "Resistencia al cambio, miedo a lo desconocido, estancamiento.", imageSlug: "death" },
  { id: 14, name: "Temperance", nameEs: "La Templanza", arcana: "major", suit: null, element: "fire", number: 14, keywords: ["equilibrio", "moderacion", "paciencia", "armonia"], meaningUpright: "Encuentra el balance en tu vida. La moderacion y la paciencia traen armonia.", meaningReversed: "Desequilibrio, excesos, impaciencia, falta de vision a largo plazo.", imageSlug: "temperance" },
  { id: 15, name: "The Devil", nameEs: "El Diablo", arcana: "major", suit: null, element: "earth", number: 15, keywords: ["atadura", "sombra", "tentacion", "materialismo"], meaningUpright: "Examina que te tiene atado. Las cadenas que ves son mas fragiles de lo que piensas.", meaningReversed: "Liberacion de ataduras, enfrentar la sombra, romper patrones.", imageSlug: "devil" },
  { id: 16, name: "The Tower", nameEs: "La Torre", arcana: "major", suit: null, element: "fire", number: 16, keywords: ["destruccion", "revelacion", "cambio subito", "liberacion"], meaningUpright: "Lo que se derrumba necesitaba caer. De las ruinas nace algo mas autentico.", meaningReversed: "Miedo al desastre, evitar lo inevitable, cambio retrasado.", imageSlug: "tower" },
  { id: 17, name: "The Star", nameEs: "La Estrella", arcana: "major", suit: null, element: "air", number: 17, keywords: ["esperanza", "inspiracion", "serenidad", "renovacion"], meaningUpright: "Despues de la tormenta viene la calma. La esperanza y la inspiracion te guian.", meaningReversed: "Falta de fe, desesperanza, desconexion espiritual.", imageSlug: "star" },
  { id: 18, name: "The Moon", nameEs: "La Luna", arcana: "major", suit: null, element: "water", number: 18, keywords: ["ilusion", "subconsciente", "miedo", "intuicion"], meaningUpright: "No todo es lo que parece. Confia en tu intuicion para navegar la incertidumbre.", meaningReversed: "Confusion disipandose, miedos enfrentados, verdad emergiendo.", imageSlug: "moon" },
  { id: 19, name: "The Sun", nameEs: "El Sol", arcana: "major", suit: null, element: "fire", number: 19, keywords: ["alegria", "exito", "vitalidad", "claridad"], meaningUpright: "Exito, alegria y vitalidad. Todo se ilumina y la claridad llega a tu vida.", meaningReversed: "Optimismo excesivo, quemarse, falta de claridad temporal.", imageSlug: "sun" },
  { id: 20, name: "Judgement", nameEs: "El Juicio", arcana: "major", suit: null, element: "fire", number: 20, keywords: ["renacimiento", "llamado", "absolucion", "despertar"], meaningUpright: "Un despertar espiritual te llama. Es momento de evaluar tu camino y renacer.", meaningReversed: "Autocritica excesiva, negarse al llamado, dudas sobre el proposito.", imageSlug: "judgement" },
  { id: 21, name: "The World", nameEs: "El Mundo", arcana: "major", suit: null, element: "earth", number: 21, keywords: ["completitud", "logro", "integracion", "celebracion"], meaningUpright: "Un ciclo se completa con exito. Celebra tus logros y preparate para lo nuevo.", meaningReversed: "Falta de cierre, metas incompletas, retraso en la realizacion.", imageSlug: "world" },
];

// =============================================
// ARCANOS MENORES — BASTOS (Wands / Fuego)
// =============================================
const WANDS: TarotCard[] = [
  { id: 22, name: "Ace of Wands", nameEs: "As de Bastos", arcana: "minor", suit: "wands", element: "fire", number: 1, keywords: ["inspiracion", "potencial", "creacion"], meaningUpright: "Una chispa de inspiracion enciende un nuevo camino creativo. Actua ahora.", meaningReversed: "Retrasos, falta de motivacion, energia bloqueada.", imageSlug: "wands-01" },
  { id: 23, name: "Two of Wands", nameEs: "Dos de Bastos", arcana: "minor", suit: "wands", element: "fire", number: 2, keywords: ["planificacion", "decision", "vision"], meaningUpright: "Tienes el mundo en tus manos. Planifica tu siguiente gran movimiento.", meaningReversed: "Miedo a lo desconocido, mala planificacion, indecision.", imageSlug: "wands-02" },
  { id: 24, name: "Three of Wands", nameEs: "Tres de Bastos", arcana: "minor", suit: "wands", element: "fire", number: 3, keywords: ["expansion", "prevision", "progreso"], meaningUpright: "Tus planes toman forma. La expansion y el progreso estan en camino.", meaningReversed: "Obstaculos inesperados, falta de prevision, retrasos.", imageSlug: "wands-03" },
  { id: 25, name: "Four of Wands", nameEs: "Cuatro de Bastos", arcana: "minor", suit: "wands", element: "fire", number: 4, keywords: ["celebracion", "hogar", "armonia"], meaningUpright: "Celebracion y estabilidad. Un momento de alegria compartida y armonia en el hogar.", meaningReversed: "Conflictos en el hogar, falta de armonia, celebracion pospuesta.", imageSlug: "wands-04" },
  { id: 26, name: "Five of Wands", nameEs: "Cinco de Bastos", arcana: "minor", suit: "wands", element: "fire", number: 5, keywords: ["conflicto", "competencia", "tension"], meaningUpright: "Competencia y conflictos menores. Usa la tension como combustible creativo.", meaningReversed: "Evitar conflictos, resolver diferencias, encontrar acuerdos.", imageSlug: "wands-05" },
  { id: 27, name: "Six of Wands", nameEs: "Seis de Bastos", arcana: "minor", suit: "wands", element: "fire", number: 6, keywords: ["victoria", "reconocimiento", "triunfo"], meaningUpright: "Victoria publica y reconocimiento. Tu esfuerzo da frutos visibles.", meaningReversed: "Ego inflado, falta de reconocimiento, exito efimero.", imageSlug: "wands-06" },
  { id: 28, name: "Seven of Wands", nameEs: "Siete de Bastos", arcana: "minor", suit: "wands", element: "fire", number: 7, keywords: ["defensa", "perseverancia", "desafio"], meaningUpright: "Defiende tu posicion con valor. Tienes la ventaja aunque el desafio sea grande.", meaningReversed: "Sentirse abrumado, rendirse, perder terreno.", imageSlug: "wands-07" },
  { id: 29, name: "Eight of Wands", nameEs: "Ocho de Bastos", arcana: "minor", suit: "wands", element: "fire", number: 8, keywords: ["velocidad", "accion", "movimiento"], meaningUpright: "Todo se acelera. Noticias rapidas, viajes y movimiento vertiginoso.", meaningReversed: "Retrasos, frustracion, esperar el momento correcto.", imageSlug: "wands-08" },
  { id: 30, name: "Nine of Wands", nameEs: "Nueve de Bastos", arcana: "minor", suit: "wands", element: "fire", number: 9, keywords: ["resiliencia", "persistencia", "ultima prueba"], meaningUpright: "Casi llegas. Una ultima prueba antes de la victoria. No te rindas.", meaningReversed: "Agotamiento, paranoia, resistencia innecesaria.", imageSlug: "wands-09" },
  { id: 31, name: "Ten of Wands", nameEs: "Diez de Bastos", arcana: "minor", suit: "wands", element: "fire", number: 10, keywords: ["carga", "responsabilidad", "esfuerzo"], meaningUpright: "Cargas demasiado. Delega o prioriza antes de que el peso te aplaste.", meaningReversed: "Soltar cargas, delegar, liberar responsabilidades innecesarias.", imageSlug: "wands-10" },
  { id: 32, name: "Page of Wands", nameEs: "Sota de Bastos", arcana: "minor", suit: "wands", element: "fire", number: 11, keywords: ["entusiasmo", "exploracion", "mensaje"], meaningUpright: "Un mensaje inspirador llega. Energia joven y entusiasta abre nuevas puertas.", meaningReversed: "Ideas sin accion, impulsividad, falta de direccion.", imageSlug: "wands-page" },
  { id: 33, name: "Knight of Wands", nameEs: "Caballero de Bastos", arcana: "minor", suit: "wands", element: "fire", number: 12, keywords: ["pasion", "aventura", "impulsividad"], meaningUpright: "Lanzate a la aventura con pasion. La energia es alta y el momento es ahora.", meaningReversed: "Impulsividad destructiva, frustracion, energia dispersa.", imageSlug: "wands-knight" },
  { id: 34, name: "Queen of Wands", nameEs: "Reina de Bastos", arcana: "minor", suit: "wands", element: "fire", number: 13, keywords: ["confianza", "carisma", "determinacion"], meaningUpright: "Brilla con confianza y carisma. Tu energia magnetica atrae lo que necesitas.", meaningReversed: "Inseguridad disfrazada, celos, demandante.", imageSlug: "wands-queen" },
  { id: 35, name: "King of Wands", nameEs: "Rey de Bastos", arcana: "minor", suit: "wands", element: "fire", number: 14, keywords: ["liderazgo", "vision", "emprendimiento"], meaningUpright: "Lidera con vision y audacia. Tu energia emprendedora inspira a otros.", meaningReversed: "Autoritarismo, expectativas irreales, tirano.", imageSlug: "wands-king" },
];

// =============================================
// ARCANOS MENORES — COPAS (Cups / Agua)
// =============================================
const CUPS: TarotCard[] = [
  { id: 36, name: "Ace of Cups", nameEs: "As de Copas", arcana: "minor", suit: "cups", element: "water", number: 1, keywords: ["amor", "emocion", "intuicion"], meaningUpright: "Un nuevo amor o conexion emocional profunda se abre ante ti.", meaningReversed: "Emociones bloqueadas, amor no correspondido, vacio emocional.", imageSlug: "cups-01" },
  { id: 37, name: "Two of Cups", nameEs: "Dos de Copas", arcana: "minor", suit: "cups", element: "water", number: 2, keywords: ["union", "asociacion", "atraccion"], meaningUpright: "Union armoniosa entre dos almas. Una relacion especial se fortalece.", meaningReversed: "Desequilibrio en la relacion, ruptura, desconfianza.", imageSlug: "cups-02" },
  { id: 38, name: "Three of Cups", nameEs: "Tres de Copas", arcana: "minor", suit: "cups", element: "water", number: 3, keywords: ["celebracion", "amistad", "comunidad"], meaningUpright: "Celebracion con seres queridos. La amistad y la comunidad te nutren.", meaningReversed: "Excesos sociales, chismes, aislamiento del grupo.", imageSlug: "cups-03" },
  { id: 39, name: "Four of Cups", nameEs: "Cuatro de Copas", arcana: "minor", suit: "cups", element: "water", number: 4, keywords: ["apatia", "contemplacion", "insatisfaccion"], meaningUpright: "Algo nuevo se ofrece pero no lo ves. Sal de la apatia y mira a tu alrededor.", meaningReversed: "Nueva motivacion, aceptar oportunidades, despertar del letargo.", imageSlug: "cups-04" },
  { id: 40, name: "Five of Cups", nameEs: "Cinco de Copas", arcana: "minor", suit: "cups", element: "water", number: 5, keywords: ["perdida", "duelo", "arrepentimiento"], meaningUpright: "El dolor es real, pero no mires solo lo perdido. Aun hay copas en pie.", meaningReversed: "Aceptacion, perdon, seguir adelante despues de la perdida.", imageSlug: "cups-05" },
  { id: 41, name: "Six of Cups", nameEs: "Seis de Copas", arcana: "minor", suit: "cups", element: "water", number: 6, keywords: ["nostalgia", "inocencia", "recuerdos"], meaningUpright: "Recuerdos dulces y conexiones del pasado traen alegria al presente.", meaningReversed: "Vivir en el pasado, idealizacion, no avanzar.", imageSlug: "cups-06" },
  { id: 42, name: "Seven of Cups", nameEs: "Siete de Copas", arcana: "minor", suit: "cups", element: "water", number: 7, keywords: ["fantasia", "opciones", "ilusion"], meaningUpright: "Muchas opciones pero no todas son reales. Distingue el sueno de la realidad.", meaningReversed: "Claridad de eleccion, poner los pies en la tierra, decision firme.", imageSlug: "cups-07" },
  { id: 43, name: "Eight of Cups", nameEs: "Ocho de Copas", arcana: "minor", suit: "cups", element: "water", number: 8, keywords: ["abandono", "busqueda", "trascendencia"], meaningUpright: "Dejas atras lo conocido buscando algo mas profundo. El viaje interior llama.", meaningReversed: "Miedo a dejar atras, apego, evitar el crecimiento.", imageSlug: "cups-08" },
  { id: 44, name: "Nine of Cups", nameEs: "Nueve de Copas", arcana: "minor", suit: "cups", element: "water", number: 9, keywords: ["satisfaccion", "deseo cumplido", "placer"], meaningUpright: "La carta del deseo cumplido. Satisfaccion emocional y gratitud profunda.", meaningReversed: "Materialismo, deseos superficiales, insatisfaccion oculta.", imageSlug: "cups-09" },
  { id: 45, name: "Ten of Cups", nameEs: "Diez de Copas", arcana: "minor", suit: "cups", element: "water", number: 10, keywords: ["felicidad", "familia", "armonia total"], meaningUpright: "Felicidad plena en el hogar y las relaciones. El arcoiris despues de la tormenta.", meaningReversed: "Conflictos familiares, valores desalineados, felicidad rota.", imageSlug: "cups-10" },
  { id: 46, name: "Page of Cups", nameEs: "Sota de Copas", arcana: "minor", suit: "cups", element: "water", number: 11, keywords: ["creatividad", "mensaje", "sensibilidad"], meaningUpright: "Un mensaje emocional o creativo llega. Abraza tu lado sensible y sonador.", meaningReversed: "Inmadurez emocional, bloqueo creativo, mensaje confuso.", imageSlug: "cups-page" },
  { id: 47, name: "Knight of Cups", nameEs: "Caballero de Copas", arcana: "minor", suit: "cups", element: "water", number: 12, keywords: ["romance", "encanto", "propuesta"], meaningUpright: "Un romantico soñador aparece. Una propuesta o invitacion especial se acerca.", meaningReversed: "Ilusion romantica, promesas vacias, decepcion sentimental.", imageSlug: "cups-knight" },
  { id: 48, name: "Queen of Cups", nameEs: "Reina de Copas", arcana: "minor", suit: "cups", element: "water", number: 13, keywords: ["empatia", "intuicion", "compasion"], meaningUpright: "Conecta con tu empatia e intuicion. Cuida de otros sin olvidarte de ti.", meaningReversed: "Co-dependencia, emociones desbordadas, martirio.", imageSlug: "cups-queen" },
  { id: 49, name: "King of Cups", nameEs: "Rey de Copas", arcana: "minor", suit: "cups", element: "water", number: 14, keywords: ["equilibrio emocional", "diplomacia", "sabiduria"], meaningUpright: "Dominio emocional con compasion. Lidera desde el corazon con sabiduria.", meaningReversed: "Manipulacion emocional, represion, volatilidad oculta.", imageSlug: "cups-king" },
];

// =============================================
// ARCANOS MENORES — ESPADAS (Swords / Aire)
// =============================================
const SWORDS: TarotCard[] = [
  { id: 50, name: "Ace of Swords", nameEs: "As de Espadas", arcana: "minor", suit: "swords", element: "air", number: 1, keywords: ["claridad", "verdad", "avance mental"], meaningUpright: "Un momento de claridad mental absoluta. La verdad corta a traves de la confusion.", meaningReversed: "Confusion, ideas falsas, uso destructivo del intelecto.", imageSlug: "swords-01" },
  { id: 51, name: "Two of Swords", nameEs: "Dos de Espadas", arcana: "minor", suit: "swords", element: "air", number: 2, keywords: ["indecision", "bloqueo", "negacion"], meaningUpright: "Una decision dificil te paraliza. Quitate la venda y enfrenta la realidad.", meaningReversed: "Informacion revelada, decision tomada, fin del bloqueo.", imageSlug: "swords-02" },
  { id: 52, name: "Three of Swords", nameEs: "Tres de Espadas", arcana: "minor", suit: "swords", element: "air", number: 3, keywords: ["dolor", "corazon roto", "traicion"], meaningUpright: "Dolor necesario para sanar. Permite que el duelo limpie tu corazon.", meaningReversed: "Recuperacion del dolor, perdon, cicatrices que sanan.", imageSlug: "swords-03" },
  { id: 53, name: "Four of Swords", nameEs: "Cuatro de Espadas", arcana: "minor", suit: "swords", element: "air", number: 4, keywords: ["descanso", "recuperacion", "meditacion"], meaningUpright: "Tu mente necesita descanso. Medita, duerme, recupera fuerzas.", meaningReversed: "Inquietud, burnout, negarse al descanso necesario.", imageSlug: "swords-04" },
  { id: 54, name: "Five of Swords", nameEs: "Cinco de Espadas", arcana: "minor", suit: "swords", element: "air", number: 5, keywords: ["derrota", "conflicto", "victoria pirrica"], meaningUpright: "Ganar a cualquier costo tiene un precio. Evalua si la batalla vale la pena.", meaningReversed: "Reconciliacion, aprender de la derrota, dejar ir el rencor.", imageSlug: "swords-05" },
  { id: 55, name: "Six of Swords", nameEs: "Seis de Espadas", arcana: "minor", suit: "swords", element: "air", number: 6, keywords: ["transicion", "viaje", "alivio gradual"], meaningUpright: "Dejas aguas turbulentas atras. La transicion es lenta pero segura.", meaningReversed: "Resistencia a moverse, equipaje emocional, estancamiento.", imageSlug: "swords-06" },
  { id: 56, name: "Seven of Swords", nameEs: "Siete de Espadas", arcana: "minor", suit: "swords", element: "air", number: 7, keywords: ["engano", "estrategia", "sigilo"], meaningUpright: "Alguien no juega limpio (quiza tu). Revisa tus estrategias y motivaciones.", meaningReversed: "Verdad descubierta, confesar, abandonar el engano.", imageSlug: "swords-07" },
  { id: 57, name: "Eight of Swords", nameEs: "Ocho de Espadas", arcana: "minor", suit: "swords", element: "air", number: 8, keywords: ["restriccion", "prision mental", "victimismo"], meaningUpright: "Te sientes atrapado pero las cadenas son mentales. Puedes liberarte.", meaningReversed: "Liberacion mental, nueva perspectiva, empoderamiento.", imageSlug: "swords-08" },
  { id: 58, name: "Nine of Swords", nameEs: "Nueve de Espadas", arcana: "minor", suit: "swords", element: "air", number: 9, keywords: ["ansiedad", "pesadillas", "preocupacion"], meaningUpright: "La ansiedad te consume de noche. Tus miedos son peores que la realidad.", meaningReversed: "Esperanza despues de la oscuridad, buscar ayuda, soltar la angustia.", imageSlug: "swords-09" },
  { id: 59, name: "Ten of Swords", nameEs: "Diez de Espadas", arcana: "minor", suit: "swords", element: "air", number: 10, keywords: ["fin doloroso", "tocar fondo", "renacimiento"], meaningUpright: "Has tocado fondo. Pero el unico camino desde aqui es hacia arriba.", meaningReversed: "Recuperacion, resurreccion, lo peor ya paso.", imageSlug: "swords-10" },
  { id: 60, name: "Page of Swords", nameEs: "Sota de Espadas", arcana: "minor", suit: "swords", element: "air", number: 11, keywords: ["curiosidad", "vigilancia", "mensaje"], meaningUpright: "Mente agil y curiosa. Mantente alerta, una noticia importante se acerca.", meaningReversed: "Chismes, espionaje, ideas sin fundamento.", imageSlug: "swords-page" },
  { id: 61, name: "Knight of Swords", nameEs: "Caballero de Espadas", arcana: "minor", suit: "swords", element: "air", number: 12, keywords: ["accion rapida", "ambicion", "determinacion"], meaningUpright: "Accion rapida y decidida. Corta a traves de los obstaculos con tu intelecto.", meaningReversed: "Imprudencia, agresion verbal, actuar sin pensar.", imageSlug: "swords-knight" },
  { id: 62, name: "Queen of Swords", nameEs: "Reina de Espadas", arcana: "minor", suit: "swords", element: "air", number: 13, keywords: ["independencia", "percepcion", "honestidad directa"], meaningUpright: "Claridad mental e independencia. Comunica la verdad con precision y gracia.", meaningReversed: "Frialdad, crueldad verbal, aislamiento emocional.", imageSlug: "swords-queen" },
  { id: 63, name: "King of Swords", nameEs: "Rey de Espadas", arcana: "minor", suit: "swords", element: "air", number: 14, keywords: ["autoridad intelectual", "etica", "verdad"], meaningUpright: "Autoridad justa basada en la verdad y la logica. Toma decisiones con claridad.", meaningReversed: "Abuso de poder intelectual, manipulacion, tirano frio.", imageSlug: "swords-king" },
];

// =============================================
// ARCANOS MENORES — OROS (Pentacles / Tierra)
// =============================================
const PENTACLES: TarotCard[] = [
  { id: 64, name: "Ace of Pentacles", nameEs: "As de Oros", arcana: "minor", suit: "pentacles", element: "earth", number: 1, keywords: ["oportunidad", "prosperidad", "manifestacion"], meaningUpright: "Una oportunidad material se presenta. Semilla de prosperidad y abundancia.", meaningReversed: "Oportunidad perdida, mala inversion, avaricia.", imageSlug: "pentacles-01" },
  { id: 65, name: "Two of Pentacles", nameEs: "Dos de Oros", arcana: "minor", suit: "pentacles", element: "earth", number: 2, keywords: ["equilibrio", "adaptacion", "multitarea"], meaningUpright: "Malabares con tus recursos. Adaptate y encuentra el equilibrio financiero.", meaningReversed: "Desorganizacion, estres financiero, prioridades desordenadas.", imageSlug: "pentacles-02" },
  { id: 66, name: "Three of Pentacles", nameEs: "Tres de Oros", arcana: "minor", suit: "pentacles", element: "earth", number: 3, keywords: ["trabajo en equipo", "maestria", "colaboracion"], meaningUpright: "El trabajo en equipo produce resultados excelentes. Tu habilidad es reconocida.", meaningReversed: "Falta de colaboracion, trabajo mediocre, conflictos laborales.", imageSlug: "pentacles-03" },
  { id: 67, name: "Four of Pentacles", nameEs: "Cuatro de Oros", arcana: "minor", suit: "pentacles", element: "earth", number: 4, keywords: ["seguridad", "control", "posesividad"], meaningUpright: "Proteges lo tuyo con celo. Pero cuidado con volverse demasiado posesivo.", meaningReversed: "Generosidad, soltar el control, compartir recursos.", imageSlug: "pentacles-04" },
  { id: 68, name: "Five of Pentacles", nameEs: "Cinco de Oros", arcana: "minor", suit: "pentacles", element: "earth", number: 5, keywords: ["escasez", "dificultad", "exclusion"], meaningUpright: "Tiempos dificiles financieros. Pero hay ayuda disponible si la buscas.", meaningReversed: "Recuperacion economica, encontrar apoyo, fin de la escasez.", imageSlug: "pentacles-05" },
  { id: 69, name: "Six of Pentacles", nameEs: "Seis de Oros", arcana: "minor", suit: "pentacles", element: "earth", number: 6, keywords: ["generosidad", "caridad", "reciprocidad"], meaningUpright: "Dar y recibir en equilibrio. La generosidad regresa multiplicada.", meaningReversed: "Deudas, generosidad con condiciones, desigualdad.", imageSlug: "pentacles-06" },
  { id: 70, name: "Seven of Pentacles", nameEs: "Siete de Oros", arcana: "minor", suit: "pentacles", element: "earth", number: 7, keywords: ["paciencia", "inversion", "evaluacion"], meaningUpright: "Evalua el fruto de tu esfuerzo. La paciencia es clave para la cosecha.", meaningReversed: "Impaciencia, inversion sin retorno, mala gestion.", imageSlug: "pentacles-07" },
  { id: 71, name: "Eight of Pentacles", nameEs: "Ocho de Oros", arcana: "minor", suit: "pentacles", element: "earth", number: 8, keywords: ["artesania", "dedicacion", "aprendizaje"], meaningUpright: "Dedicacion al oficio. Tu disciplina y aprendizaje constante dan resultados.", meaningReversed: "Perfeccionismo paralizante, trabajo repetitivo, falta de motivacion.", imageSlug: "pentacles-08" },
  { id: 72, name: "Nine of Pentacles", nameEs: "Nueve de Oros", arcana: "minor", suit: "pentacles", element: "earth", number: 9, keywords: ["abundancia", "lujo", "autosuficiencia"], meaningUpright: "Disfrutas los frutos de tu trabajo. Independencia y abundancia merecida.", meaningReversed: "Sobre-inversion en lo material, soledad dorada, dependencia financiera.", imageSlug: "pentacles-09" },
  { id: 73, name: "Ten of Pentacles", nameEs: "Diez de Oros", arcana: "minor", suit: "pentacles", element: "earth", number: 10, keywords: ["legado", "riqueza", "herencia"], meaningUpright: "Riqueza duradera y legado familiar. La prosperidad abarca generaciones.", meaningReversed: "Conflictos por herencia, perdida financiera, inestabilidad familiar.", imageSlug: "pentacles-10" },
  { id: 74, name: "Page of Pentacles", nameEs: "Sota de Oros", arcana: "minor", suit: "pentacles", element: "earth", number: 11, keywords: ["estudio", "oportunidad", "ambicion joven"], meaningUpright: "Una oportunidad de aprendizaje o financiera aparece. Abrazala con disciplina.", meaningReversed: "Falta de progreso, procrastinacion, oportunidad desperdiciada.", imageSlug: "pentacles-page" },
  { id: 75, name: "Knight of Pentacles", nameEs: "Caballero de Oros", arcana: "minor", suit: "pentacles", element: "earth", number: 12, keywords: ["eficiencia", "rutina", "responsabilidad"], meaningUpright: "Avance lento pero seguro. Tu constancia y responsabilidad son tu mayor fortaleza.", meaningReversed: "Estancamiento, terquedad, obsesion con la perfeccion.", imageSlug: "pentacles-knight" },
  { id: 76, name: "Queen of Pentacles", nameEs: "Reina de Oros", arcana: "minor", suit: "pentacles", element: "earth", number: 13, keywords: ["nutricion", "practicidad", "seguridad"], meaningUpright: "Creas un ambiente seguro y nutritivo. Prosperidad practica y generosa.", meaningReversed: "Descuido del hogar, inseguridad financiera, exceso de trabajo.", imageSlug: "pentacles-queen" },
  { id: 77, name: "King of Pentacles", nameEs: "Rey de Oros", arcana: "minor", suit: "pentacles", element: "earth", number: 14, keywords: ["riqueza", "negocios", "disciplina"], meaningUpright: "Dominio del mundo material. Exito en negocios a traves de disciplina y vision.", meaningReversed: "Avaricia, obsesion por el dinero, corrupcion.", imageSlug: "pentacles-king" },
];

// =============================================
// MAZO COMPLETO
// =============================================
export const TAROT_DECK: TarotCard[] = [
  ...MAJOR_ARCANA,
  ...WANDS,
  ...CUPS,
  ...SWORDS,
  ...PENTACLES,
];

/** Obtener carta por ID */
export function getCardById(id: number): TarotCard | undefined {
  return TAROT_DECK.find((c) => c.id === id);
}

/** Barajar el mazo (Fisher-Yates) y sacar N cartas */
export function drawCards(count: number): Array<{ card: TarotCard; reversed: boolean }> {
  const shuffled = Array.from(TAROT_DECK);
  for (let i = shuffled.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    const temp = shuffled[i];
    shuffled[i] = shuffled[j];
    shuffled[j] = temp;
  }
  return shuffled.slice(0, count).map((card) => ({
    card,
    reversed: Math.random() < 0.3, // 30% probabilidad de invertida
  }));
}
